modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="chaosawakened"
version="1.0.0"
displayName="ChaosAwakened"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Minecraft, MCreator"

[[dependencies.chaosawakened]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




